function setDefaultFigureProperties()
set(groot,'defaultLineLineWidth',2.5) 
set(0,'DefaultaxesLineWidth', 1.5) 
set(0,'DefaultaxesFontSize', 20) 
set(0,'DefaultaxesFontWeight', 'normal') 
set(0,'DefaultTextFontSize', 20) 
set(0,'DefaultaxesFontName', 'Times new Roman') 
set(0,'DefaultlegendFontName', 'Times new Roman')
set(0,'defaultAxesXMinorGrid','off') 
set(0,'defaultAxesYMinorGrid','off')
set(0,'defaultAxesZMinorGrid','off')
set(0,'defaultAxesBox','on')
set(0,'DefaultTextInterpreter', 'latex')
end